#!/usr/bin/perl -w
use strict;
BEGIN { unshift @INC, qw( lib extlib ) }
use MT::Bootstrap::CLI App => 'TemplateUpgrader::Tool::Upgrade';

__END__

=head1 TemplateUpgrader::Tool::Upgrade

TemplateUpgrader/tools/upgrade - A command-line template upgrader

=head1 DESCRIPTION

This plugin provides a framework for upgrading Melody/Movable Type templates
and provides a command-line interface through which to operate.

=head1 SYNOPSIS

 ./plugins/TemplateUpgrader/tools/upgrade [options]

Use the --help flag for more information

=head1 OPTIONS

=over 8


=item B<-b, --blog (ID|NAME)>

The ID or exact name of the blog to be used for template upgrade

=item B<-t, --template (ID|IDENTIFIER|NAME)>

OPTIONAL: This parameter is specified when a single template is to be
upgraded. The --blog parameter is required company unless you specify the
template ID.

=item B<-d, --debug>

If specified, performs a dry-run only which modifies nothing.

=item B<-h>

Prints a brief usage message.

=item B<--help>

Displays the command usage and option descriptions.

=item B<--man>

Displays the full manual page including, most notably, examples of usage.

=back

=head1 SETTING YOUR MT_HOME ENVIRONMENT VARIABLE

For all examples shown below, it is assumed that you have properly set your
MT_HOME environment variable. With this set, you are free to run this program
from anywhere, not just your MT directory.

Setting MT_HOME is usually done through one of the following methods:

=over 8

=item B<Export declaration:> 

 prompt> export MT_HOME="/home/www/cgi-bin/mt"
 prompt> /path/to/script [options] args

=item B<Temporary assignment:>

  prompt> MT_HOME="/path/to/MT" /path/to/script [options] args

=back

If you only have a single MT directory, it's best to use an export
declaration in your shell's init script (e.g. .bashrc/.bash_profile,
.cshrc, etc).

=cut

